feat: auto apply checksum when starting VSCode
RimuruChan/vscode-fix-checksums pull request #6
Opened 2024-12-06 06:12 UTC by Zylsjsp

Auto apply feature from [iewnfod/vscode-fix-checksums](https://github.com/iewnfod/vscode-fix-checksums)

2024-12-06 14:38 UTC, RimuruChan requested changes

2024-12-06 14:38 UTC, RimuruChan commented on src/extension.js
> +  apply(auto)
Seems that it always applies whether you set auto fix or not. The option just hides the message, not controls the behavior

2024-12-06 16:15 UTC, zent1n0 commented on src/extension.js
> +  apply(auto)
Yes, seems auto only controls message, and the logic should be fine with a if clause.

However, the plugin code doesn't load with VSCode extension server starting, but on the first command was executed, thus the calling seems no sense.

Or shall we set the plugin activate on start up to trigger an Apply event?

2025-06-22 15:03 UTC, merged

2025-06-22 17:02 UTC, zent1n0 commented
Do you think it would be a better user experience if auto apply doesn't prompt when checksums are not changed?

2025-06-23 12:07 UTC, RimuruChan commented
This may be a security risk. If necessary, I suggest adding an independent option control to ensure that users explicitly ignore the risk.

If you have time, you can implement it and open a new PR.